#ifndef SOLIMLIBFORQT_GLOBAL_H
#define SOLIMLIBFORQT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SOLIMLIBFORQT_LIBRARY)
#  define SOLIMLIBFORQT_EXPORT Q_DECL_EXPORT
#else
#  define SOLIMLIBFORQT_EXPORT Q_DECL_IMPORT
#endif

#endif // SOLIMLIBFORQT_GLOBAL_H
